import React, { useState } from 'react';

// Stage definitions
type WizardStage = 'intent' | 'research' | 'generation';

interface SkillIntent {
    name: string;
    description: string;
    purpose: string;
    context?: string;
}

interface ResearchResult {
    bestPractices: string[];
    tools: string[];
    patterns: string[];
    sources: { title: string; url: string }[];
}

const SkillFactory: React.FC = () => {
    const [currentStage, setCurrentStage] = useState<WizardStage>('intent');
    const [intent, setIntent] = useState<SkillIntent>({
        name: '',
        description: '',
        purpose: '',
        context: ''
    });
    const [researchResults, setResearchResults] = useState<ResearchResult | null>(null);
    const [isResearching, setIsResearching] = useState(false);
    const [generatedContent, setGeneratedContent] = useState<string>('');
    const [isGenerating, setIsGenerating] = useState(false);

    // Generate SKILL.md content from research results
    const generateSkillContent = () => {
        if (!researchResults) return '';

        const timestamp = new Date().toISOString().split('T')[0];

        return `---
name: ${intent.name}
description: ${intent.description}
version: 1.0.0
created: ${timestamp}
updated: ${timestamp}
---

# ${intent.name}

## 📋 Overview

${intent.description}

**Purpose:** ${intent.purpose}

${intent.context ? `**Additional Context:** ${intent.context}\n` : ''}

## 🎯 When to Use This Skill

${intent.purpose}

Key use cases:
${researchResults.bestPractices.slice(0, 3).map(practice => `- ${practice}`).join('\n')}

## 🛠️ Tools & Technologies

The following tools are recommended for implementing this skill:

${researchResults.tools.map(tool => `- **${tool}**`).join('\n')}

## 📚 Best Practices

${researchResults.bestPractices.map((practice, i) => `${i + 1}. ${practice}`).join('\n')}

## 🏗️ Architecture Patterns

${researchResults.patterns.map(pattern => `- ${pattern}`).join('\n')}

## 📖 Implementation Guide

### Step 1: Setup
- Install and configure required tools
- Set up development environment
- Initialize project structure

### Step 2: Core Implementation
- Follow the architecture patterns outlined above
- Apply best practices for code quality
- Implement comprehensive error handling

### Step 3: Testing & Validation
- Write unit tests with high coverage
- Perform integration testing
- Validate against requirements

### Step 4: Documentation
- Document all APIs and interfaces
- Add inline code comments
- Create usage examples

## 🔗 References & Resources

${researchResults.sources.map(source => `- [${source.title}](${source.url})`).join('\n')}

## ✅ Quality Checklist

- [ ] Code follows SOLID principles
- [ ] Comprehensive error handling implemented
- [ ] Unit tests written with \u003e80% coverage
- [ ] Documentation is clear and complete
- [ ] Security best practices applied
- [ ] Performance optimized
- [ ] Code reviewed and approved

---

**Generated by:** Vibecode AI Skill Factory  
**Generated on:** ${new Date().toLocaleString('vi-VN', { timeZone: 'Asia/Ho_Chi_Minh' })}
`;
    };

    // Auto-generate skill content when entering generation stage
    React.useEffect(() => {
        if (currentStage === 'generation' && !generatedContent && researchResults) {
            setIsGenerating(true);
            setTimeout(() => {
                const content = generateSkillContent();
                setGeneratedContent(content);
                setIsGenerating(false);
            }, 1500); // Simulate generation time
        }
    }, [currentStage, generatedContent, researchResults]);

    const handleIntentSubmit = async () => {
        if (!intent.name || !intent.description || !intent.purpose) {
            alert('Vui lòng điền đầy đủ thông tin!');
            return;
        }

        setIsResearching(true);
        setCurrentStage('research');

        try {
            // Call Gemini AI via Tauri command for real intelligent generation
            const { invoke } = await import('@tauri-apps/api/core');

            const result: any = await invoke('generate_skill_with_gemini', {
                intent: {
                    name: intent.name,
                    description: intent.description,
                    purpose: intent.purpose,
                    context: intent.context || null
                }
            });

            if (result.success) {
                setResearchResults({
                    bestPractices: result.best_practices,
                    tools: result.tools,
                    patterns: result.patterns,
                    sources: [
                        { title: 'Generated by Gemini 1.5 Flash AI', url: 'https://ai.google.dev/' },
                        { title: `Best practices for ${intent.name}`, url: '#' }
                    ]
                });

                // Set the generated content directly
                setGeneratedContent(result.skill_content);
            } else {
                throw new Error(result.error || 'Unknown error');
            }

            setIsResearching(false);
        } catch (error: any) {
            console.error('AI Generation failed:', error);
            const errorMsg = error?.toString() || 'Unknown error';

            // Show specific error - NO silent fallback
            setIsResearching(false);

            if (errorMsg.includes('chưa được cấu hình') || errorMsg.includes('API Key')) {
                alert('⚠️ Gemini API Key chưa được cấu hình.\n\nVào Settings → Nhập Gemini API Key để sử dụng AI.\n\nLấy key tại: https://aistudio.google.com/apikey');
                setCurrentStage('intent');
                return;
            }

            alert(`❌ Lỗi tạo skill với AI:\n\n${errorMsg}`);
            setCurrentStage('intent');
        }
    };

    const renderStageIndicator = () => (
        <div className="flex items-center justify-center mb-8 px-4">
            <div className={`flex flex-col items-center gap-2 ${currentStage === 'intent' ? 'opacity-100' : 'opacity-50'}`}>
                <div className={`w-8 h-8 rounded-full flex items-center justify-center font-bold text-sm ${currentStage === 'intent' ? 'bg-accent-primary text-white' : 'bg-surface border border-border-default'}`}>1</div>
                <div className="text-xs font-medium uppercase tracking-wide">Mô tả</div>
            </div>
            <div className="w-16 h-px bg-border-default mx-2" />
            <div className={`flex flex-col items-center gap-2 ${currentStage === 'research' ? 'opacity-100' : currentStage === 'generation' ? 'opacity-50' : 'opacity-50'}`}>
                <div className={`w-8 h-8 rounded-full flex items-center justify-center font-bold text-sm ${currentStage === 'research' ? 'bg-accent-primary text-white' : 'bg-surface border border-border-default'}`}>2</div>
                <div className="text-xs font-medium uppercase tracking-wide">Nghiên cứu</div>
            </div>
            <div className="w-16 h-px bg-border-default mx-2" />
            <div className={`flex flex-col items-center gap-2 ${currentStage === 'generation' ? 'opacity-100' : 'opacity-50'}`}>
                <div className={`w-8 h-8 rounded-full flex items-center justify-center font-bold text-sm ${currentStage === 'generation' ? 'bg-accent-primary text-white' : 'bg-surface border border-border-default'}`}>3</div>
                <div className="text-xs font-medium uppercase tracking-wide">Kết quả</div>
            </div>
        </div>
    );

    const renderIntentForm = () => (
        <div className="card max-w-2xl mx-auto shadow-xl">
            <div className="card-header bg-bg-surface border-b border-border-subtle p-6">
                <div>
                    <h2 className="text-xl font-semibold text-text-primary mb-1">🎯 Skill bạn muốn tạo là gì?</h2>
                    <p className="text-sm text-text-secondary">Mô tả chi tiết để AI nghiên cứu và tạo skill chuyên nghiệp</p>
                </div>
            </div>

            <div className="card-body p-6 space-y-5">
                <div className="form-group">
                    <label className="block text-sm font-medium text-text-secondary mb-2">
                        Tên Skill <span className="text-error">*</span>
                    </label>
                    <input
                        type="text"
                        placeholder="Ví dụ: Python Testing Automation"
                        value={intent.name}
                        onChange={(e) => setIntent({ ...intent, name: e.target.value })}
                        className="input"
                    />
                </div>

                <div className="form-group">
                    <label className="block text-sm font-medium text-text-secondary mb-2">
                        Mô tả (Skill này giải quyết vấn đề gì?) <span className="text-error">*</span>
                    </label>
                    <textarea
                        placeholder="Ví dụ: Tự động hóa quy trình testing cho Python projects..."
                        value={intent.description}
                        onChange={(e) => setIntent({ ...intent, description: e.target.value })}
                        className="input min-h-[100px]"
                    />
                </div>

                <div className="form-group">
                    <label className="block text-sm font-medium text-text-secondary mb-2">
                        Mục đích (Sử dụng khi nào?) <span className="text-error">*</span>
                    </label>
                    <textarea
                        placeholder="Ví dụ: Khi cần verify code quality trước khi commit, CI/CD..."
                        value={intent.purpose}
                        onChange={(e) => setIntent({ ...intent, purpose: e.target.value })}
                        className="input min-h-[80px]"
                    />
                </div>

                <div className="form-group">
                    <label className="block text-sm font-medium text-text-secondary mb-2">
                        Context bổ sung (Optional)
                    </label>
                    <textarea
                        placeholder="Thêm yêu cầu đặc biệt, constraints, hoặc preferences..."
                        value={intent.context}
                        onChange={(e) => setIntent({ ...intent, context: e.target.value })}
                        className="input min-h-[80px]"
                    />
                </div>
            </div>

            <div className="card-footer bg-bg-surface p-6 flex justify-end">
                <button
                    className="btn btn-primary btn-lg w-full sm:w-auto"
                    onClick={handleIntentSubmit}
                >
                    Tiếp theo: Research →
                </button>
            </div>
        </div>
    );

    const renderResearchStage = () => (
        <div className="card max-w-4xl mx-auto shadow-xl">
            <div className="card-header bg-bg-surface p-6 border-b border-border-subtle">
                <div>
                    <h2 className="text-xl font-semibold text-text-primary mb-1">🔍 AI đang nghiên cứu...</h2>
                    <p className="text-sm text-text-secondary">Tìm kiếm best practices và công cụ tốt nhất cho "{intent.name}"</p>
                </div>
            </div>

            <div className="card-body p-6 min-h-[400px]">
                {isResearching ? (
                    <div className="flex flex-col items-center justify-center py-12 gap-6">
                        <div className="w-12 h-12 border-4 border-border-subtle border-t-accent-primary rounded-full animate-spin" />
                        <div className="text-center">
                            <p className="text-lg font-medium text-text-primary mb-2">🤖 Đang tạo nội dung với Gemini AI...</p>
                            <div className="text-sm text-text-muted space-y-1">
                                <p>✓ Phân tích yêu cầu</p>
                                <p>✓ Tìm kiếm best practices</p>
                                <p className="animate-pulse">○ Xác định công cụ phù hợp</p>
                                <p>○ Tổng hợp patterns</p>
                            </div>
                        </div>
                    </div>
                ) : researchResults ? (
                    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                        <div className="space-y-4">
                            <h3 className="text-md font-semibold text-text-primary border-b border-border-subtle pb-2">📚 Phương pháp tốt nhất</h3>
                            <ul className="space-y-2">
                                {researchResults.bestPractices.map((practice, i) => (
                                    <li key={i} className="flex gap-2 text-sm text-text-secondary">
                                        <span className="text-accent-primary">•</span>
                                        {practice}
                                    </li>
                                ))}
                            </ul>
                        </div>

                        <div className="space-y-4">
                            <h3 className="text-md font-semibold text-text-primary border-b border-border-subtle pb-2">🛠️ Công cụ khuyến nghị</h3>
                            <div className="flex flex-wrap gap-2">
                                {researchResults.tools.map((tool, i) => (
                                    <span key={i} className="px-3 py-1 bg-bg-elevated border border-border-default rounded-full text-xs text-text-primary">
                                        {tool}
                                    </span>
                                ))}
                            </div>
                        </div>

                        <div className="col-span-1 md:col-span-2 space-y-4">
                            <h3 className="text-md font-semibold text-text-primary border-b border-border-subtle pb-2">🎯 Quy trình & Mô hình</h3>
                            <ul className="grid grid-cols-1 md:grid-cols-2 gap-2">
                                {researchResults.patterns.map((pattern, i) => (
                                    <li key={i} className="flex gap-2 text-sm text-text-secondary bg-bg-elevated p-3 rounded-lg border border-border-subtle">
                                        <span className="text-accent-primary">⚡</span>
                                        {pattern}
                                    </li>
                                ))}
                            </ul>
                        </div>
                    </div>
                ) : null}
            </div>

            {researchResults && (
                <div className="card-footer bg-bg-surface p-6 flex justify-between">
                    <button
                        className="btn btn-ghost"
                        onClick={() => setCurrentStage('intent')}
                    >
                        ← Quay lại
                    </button>
                    <button
                        className="btn btn-primary"
                        onClick={() => setCurrentStage('generation')}
                    >
                        Tiếp theo: Generate Skill →
                    </button>
                </div>
            )}
        </div>
    );

    const renderGenerationStage = () => {
        const handleDownload = () => {
            if (!generatedContent || generatedContent.trim().length < 100) {
                alert('⚠️ Nội dung skill chưa sẵn sàng.\n\nVui lòng thử lại từ bước 1.');
                return;
            }
            const blob = new Blob([generatedContent], { type: 'text/markdown;charset=utf-8' });
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = `${intent.name.toLowerCase().replace(/\s+/g, '-')}-SKILL.md`;
            document.body.appendChild(a);
            a.click();
            document.body.removeChild(a);
            URL.revokeObjectURL(url);
        };

        const handleReset = () => {
            setCurrentStage('intent');
            setIntent({ name: '', description: '', purpose: '', context: '' });
            setResearchResults(null);
            setGeneratedContent('');
            setIsResearching(false);
            setIsGenerating(false);
        };

        return (
            <div className="card max-w-4xl mx-auto shadow-xl h-full flex flex-col">
                <div className="card-header bg-bg-surface p-6 border-b border-border-subtle">
                    <div className="flex items-center gap-3">
                        <div className="w-8 h-8 rounded-full bg-success/20 flex items-center justify-center text-success">✓</div>
                        <div>
                            <h2 className="text-xl font-semibold text-text-primary mb-1">Skill Generated Successfully!</h2>
                            <p className="text-sm text-text-secondary">Xem trước nội dung SKILL.md bên dưới</p>
                        </div>
                    </div>
                </div>

                <div className="card-body p-0 flex-1 relative min-h-[500px]">
                    {isGenerating ? (
                        <div className="absolute inset-0 flex flex-col items-center justify-center bg-bg-base/50 backdrop-blur-sm z-10">
                            <div className="w-12 h-12 border-4 border-accent-primary border-t-transparent rounded-full animate-spin mb-4" />
                            <p className="text-text-primary font-medium">Đang soạn thảo SKILL.md chuyên nghiệp...</p>
                        </div>
                    ) : null}

                    {generatedContent && (
                        <textarea
                            className="w-full h-full p-6 bg-bg-base font-mono text-sm text-text-secondary resize-none focus:outline-none"
                            value={generatedContent}
                            onChange={(e) => setGeneratedContent(e.target.value)}
                            spellCheck={false}
                        />
                    )}
                </div>

                <div className="card-footer bg-bg-surface p-6 border-t border-border-subtle flex justify-between items-center">
                    <div className="text-xs text-text-muted">
                        {generatedContent.length} ký tự • {generatedContent.split('\n').length} dòng
                    </div>
                    <div className="flex gap-3">
                        <button className="btn btn-secondary" onClick={handleReset}>
                            🔄 Tạo skill mới
                        </button>
                        <button className="btn btn-primary" onClick={handleDownload}>
                            ⬇️ Tải xuống .md
                        </button>
                    </div>
                </div>
            </div>
        );
    };

    return (
        <div className="h-full p-8 overflow-y-auto bg-bg-base">
            <div className="max-w-5xl mx-auto mb-8 text-center">
                <h1 className="text-3xl font-bold text-text-primary mb-2">🏭 AI-Powered Skill Factory</h1>
                <p className="text-text-secondary">Tự động tạo skills, workflows & rules từ ý tưởng của bạn</p>
            </div>

            {renderStageIndicator()}

            <div className="max-w-5xl mx-auto pb-12">
                {currentStage === 'intent' && renderIntentForm()}
                {currentStage === 'research' && renderResearchStage()}
                {currentStage === 'generation' && renderGenerationStage()}
            </div>
        </div>
    );
};

export default SkillFactory;
